apiVersion: apps/v1
kind: Deployment
metadata:
  name: willow-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willow-web
  template:
    metadata:
      labels:
        app: willow-web
    spec:
      containers:
      - name: willow-web
        image: us-central1-docker.pkg.dev/ace-course-web-app-497605/willow-images/willow-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://willow-api-service"